<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prospace factoral calculator_number</name>
   <tag></tag>
   <elementGuidId>8793cc02-afcf-4eb3-b699-a48f2ae35f2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09d4e987-6fae-4328-8b2a-45c008141223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73a15dc6-037f-49d7-8e20-6f67858f9f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ce24484d-e7b8-4460-81d9-a630e71609a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-lg</value>
      <webElementGuid>b3e79d4b-6b44-40ff-8513-4a1f0b160ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a8cf49a3-a833-4282-b922-0d476f133f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter an integer</value>
      <webElementGuid>08cd6766-29f0-460f-8fd3-a173d1775608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;number&quot;)</value>
      <webElementGuid>97d5ac95-ed64-4fcc-8d64-cbde8ec3180c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='number']</value>
      <webElementGuid>79a26ef0-5d6b-4c2d-a609-5b5b24e2c993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2d6f7b4c-4177-4dcc-a9fc-cf139cf6ce07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'number' and @name = 'number' and @placeholder = 'Enter an integer']</value>
      <webElementGuid>e469fb01-2731-4cb3-a7e4-9ef0449996da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
