<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Please enter an integer</name>
   <tag></tag>
   <elementGuidId>76971947-46b9-43ec-b25f-edc276a9f3bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#resultDiv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='resultDiv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6425601b-a968-4d8d-80a9-eb8770c3593a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center top-space-20</value>
      <webElementGuid>ba3e9887-4b8e-48a4-a9fb-8c6706d90056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>resultDiv</value>
      <webElementGuid>26d4d38d-c3a2-415d-bf43-e3adcb0f0093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter an integer</value>
      <webElementGuid>f4a37f0a-b1a8-4223-89e2-f817bc9d3f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultDiv&quot;)</value>
      <webElementGuid>73bca015-07ca-471f-9fae-05edadd3aa2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='resultDiv']</value>
      <webElementGuid>d29812f7-b200-4df3-869a-dfcf14026891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calclate!'])[1]/following::p[1]</value>
      <webElementGuid>61e02fe9-ec64-4381-8251-2e283f801703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prospace factoral calculator'])[1]/following::p[3]</value>
      <webElementGuid>97bdcec3-4f96-46a0-a142-48a6b52be7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms and Conditions'])[1]/preceding::p[1]</value>
      <webElementGuid>d82cda16-0aac-41f6-8e3c-5479819cff15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/preceding::p[1]</value>
      <webElementGuid>15271bc9-8a47-4e9a-b4e2-bea9e9e7a4cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please enter an integer']/parent::*</value>
      <webElementGuid>9e222d38-2cf1-47c4-8341-9486f99cdcd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/p</value>
      <webElementGuid>16441e9a-e71b-4db9-b807-301a3e481492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'resultDiv' and (text() = 'Please enter an integer' or . = 'Please enter an integer')]</value>
      <webElementGuid>3ef441df-fc36-41c8-bbdc-dbe61149b183</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
